vcenter_username = "administrator@vsphere.local"
vcenter_password = "sgZiCT6oRuvD^nap#Ps)"
vcenter_allow_insecure = true
vcenter_server = "vcsa.homelab"
vcenter_datacenter = "Homelab"
vcenter_cluster = "Cluster"
esxi_host = "esxi01.homelab"
vcenter_folder = "Kubernetes"
vcenter_datastore = "datastore07"
vcenter_network = "VM Network"
ssh_username = "packer"
ssh_password = "g7cgxJriXbA5bjca"
vm_name = "ubuntu-kubes"
guest_os_type = "ubuntu64Guest"
hw_version = 17
boot_mode = "EFI"
cpu_sockets = 1
cpu_cores_per_socket = 6
mem_size = 12288
storge_controller_type = ["pvscsi"]
disk_size = 102400
thin_provision = true
vm_network_card = "vmxnet3"
vm_boot_wait = "5s"
iso_path = "[synology01] ISO/Ubuntu/ubuntu-23.10-live-server-amd64.iso"
http_directory = "http"
