vcenter_username = "administrator@vsphere.local"
vcenter_allow_insecure = true
vcenter_server = "vcsa.homelab"
vcenter_datacenter = "Homelab"
vcenter_cluster = "Cluster"
esxi_host = "esxi.homelab"
vcenter_folder = "Kubernetes"
vcenter_datastore = "datastore4"
vcenter_network = "VM Network"
network_card = "vmxnet3"
ssh_username = "packer"
vm_name = "ubuntu-kubes-v1.1"
guest_os_type = "ubuntu64Guest"
hw_version = 17
boot_mode = "efi"
total_cpu_cores = 6
cpu_cores_per_socket = 6
mem_size = 12288
storage_controller_type = ["pvscsi"]
disk_size = 102400
thin_provision = true
vm_boot_wait = "5s"
iso_path = "[synology01] ISO/Ubuntu/ubuntu-23.10-live-server-amd64.iso"
shell_scripts = ["./scripts/setup_ubuntu.sh"]
